// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3g4Ifk-unv2MvFWJydwMgRTT5NRMPG8',
    appId: '1:837848575000:web:644438fbdd0721ff07276d',
    messagingSenderId: '837848575000',
    projectId: 'dalel-app-634fe',
    authDomain: 'dalel-app-634fe.firebaseapp.com',
    storageBucket: 'dalel-app-634fe.appspot.com',
    measurementId: 'G-LD36LT7DKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQUWo21r6Ih9U7_bLIVwYpJ_Pt750yYY',
    appId: '1:837848575000:android:bfedde29b23a3f9607276d',
    messagingSenderId: '837848575000',
    projectId: 'dalel-app-634fe',
    storageBucket: 'dalel-app-634fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgTh9L1gnlylnWHC_C-IMR3q3r-yuQYIM',
    appId: '1:837848575000:ios:9ecc3328d529582207276d',
    messagingSenderId: '837848575000',
    projectId: 'dalel-app-634fe',
    storageBucket: 'dalel-app-634fe.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgTh9L1gnlylnWHC_C-IMR3q3r-yuQYIM',
    appId: '1:837848575000:ios:9ecc3328d529582207276d',
    messagingSenderId: '837848575000',
    projectId: 'dalel-app-634fe',
    storageBucket: 'dalel-app-634fe.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw3g4Ifk-unv2MvFWJydwMgRTT5NRMPG8',
    appId: '1:837848575000:web:676d406c7e3d99dc07276d',
    messagingSenderId: '837848575000',
    projectId: 'dalel-app-634fe',
    authDomain: 'dalel-app-634fe.firebaseapp.com',
    storageBucket: 'dalel-app-634fe.appspot.com',
    measurementId: 'G-ETNV5TJQRC',
  );
}
